site_name: Devops Foundations Devops.gt
nav:
    - Home: index.md
    - Creacion de Repositorio Codigo:
        - Paso 1: Paso1.md
        - Paso 2: Paso2.md
        - Paso 3: Paso3.md
        - Paso 4: Paso4.md
    - Creacion de API: 
        - Paso 5: Paso5.md
        - Paso 6: Paso6.md
        - Paso 7: Paso7.md
        - Paso 8: Paso8.md
    - Creacion de Pipeline:
        - Paso 9: Paso9.md

theme: readthedocs